name: pushimage

on:
    push:


jobs:
    pushimage:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: set up docker
              uses: docker/setup-buildx-action@v2
            - name: docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}            
            - name: build and push
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: |
                    ithatabdullah/pushtest:latest
                    ithatabdullah/pushtest:${{ github.sha }}      